# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='./db/photos/')),
                ('category', models.TextField(max_length=20)),
                ('label1', models.TextField(max_length=1)),
                ('label2', models.TextField(max_length=1)),
                ('label3', models.TextField(max_length=1)),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
